### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by jdubz666** [Jonathan53891/NFLPlayoffBracket#1]
Hi,

I'm wondering if you could tell me a little more about this?  When I run the HTML it shows blank boxes.  How would I populate these with teams.

I'm hoping to find an HTML application that I can display the current NFL playoff bracket.  Is this a manually created bracket or can it have playoff standing populated into it.

Looks great by the way.

Thanks!

**Comment by Jonathan53891** [comment]
Hey @jdubz666,

Thank you for reaching out! I want to apologize for my messy code there - this was an outdated copy that I uploaded to Github a couple months ago. Please go ahead and reupload the bracket.html file, and reupload all of the image files so you can receive all of the updated 2023/2024 playoff data.

The reason why the HTML was showing blank boxes after uploading all of the code was because the file location for the logos in the HTML file were under the following folder location (using the Ravens as an example): "media/img/nfl/ravens.png". I forgot to add the nfl folder underneath the img folder when I uploaded this a couple months ago, so it was trying to access images in a folder that didn't exist.

Please feel free to reupload the updated code so you can mitigate that issue in addition to the updated 2023 playoff teams and current NFL team logos.

Thank you!

**Comment by jdubz666** [comment]
That got it working! Cool project. Thanks @Jonathan53891

**Comment by Jonathan53891** [comment]
Anytime - have fun making your brackets!
